export const AppStrings = {
  cart: {
    title: 'Корзина',
    empty: 'Корзина пуста',
    checkout: 'Оформить заказ',
    total: 'Итого',
    remove: 'Удалить',
    quantity: 'Количество',
    volume: 'Объём',
    outOfStock: 'Нет в наличии',
    added: 'Добавлено в корзину',
    open: 'Открыть корзину',
    close: 'Закрыть корзину',
  },
  checkout: {
    title: 'Оформление заказа',
    name: 'Имя',
    phone: 'Телефон',
    namePlaceholder: 'Как к вам обращаться',
    phonePlaceholder: '+7 747 000 00 00',
    submit: 'Отправить заказ',
    submitting: 'Отправляем заказ…',
    success: 'Заказ принят. Сейчас откроется WhatsApp.',
    error: 'Не удалось оформить заказ. Попробуйте ещё раз.',
    close: 'Закрыть',
  },
  product: {
    outOfStock: 'Нет в наличии',
    addToCart: 'Добавить в корзину',
    original: 'Оригинал',
    perMl: '/ 1 мл',
  },
  admin: {
    title: 'Админка Lumira',
    login: 'Войти',
    logout: 'Выйти',
    email: 'Email',
    password: 'Пароль',
    forbidden: 'Нет доступа к админке.',
    products: 'Товары',
    orders: 'Заказы',
    inStock: 'В наличии',
    hidden: 'Скрыто',
    pricePerMl: 'Цена за мл',
    telegramSent: 'Telegram',
    status: 'Статус',
  },
} as const
