export const AppStrings = {
  cart: {
    title: 'Корзина',
    empty: 'Корзина пуста',
    toCatalog: 'Перейти в каталог',
    checkout: 'Оформить заказ',
    total: 'Итого',
    subtotal: 'Сумма товаров',
    delivery: 'Доставка: рассчитаем в WhatsApp',
    payAfter: 'к оплате после подтверждения',
    kaspiHint: 'Дальше — WhatsApp и оплата Kaspi после подтверждения.',
    remove: 'Удалить',
    quantity: 'Количество',
    decrease: 'Уменьшить количество',
    increase: 'Увеличить количество',
    volume: 'Объём',
    outOfStock: 'Нет в наличии',
    added: 'Добавлено в корзину',
    open: 'Открыть корзину',
    close: 'Закрыть корзину',
    limit: 'В корзине максимум 20 позиций',
  },
  checkout: {
    title: 'Оформление заказа',
    name: 'Имя',
    phone: 'Телефон',
    city: 'Город',
    cityPlaceholder: 'Алматы',
    namePlaceholder: 'Как к вам обращаться',
    phonePlaceholder: '+7 747 000 00 00',
    fulfillment: 'Получение',
    fulfillmentValue: 'Напишем в WhatsApp и согласуем доставку',
    payment: 'Оплата',
    paymentValue: 'Kaspi после подтверждения заказа',
    paymentHint: 'Счёт пришлём в WhatsApp после сверки состава.',
    offer: 'Согласен с офертой и политикой конфиденциальности',
    offerPrefix: 'Я согласен с условиями',
    oferta: 'публичной оферты',
    privacy: 'политикой конфиденциальности',
    submit: 'Отправить заказ',
    submitting: 'Отправляем…',
    successTitle: 'Заказ принят',
    successWhatsApp: 'Открыть WhatsApp',
    successHint: 'Можно открыть WhatsApp — текст заказа уже готов.',
    successCatalog: 'В каталог',
    kaspiAfter: 'Kaspi после подтверждения',
    error: 'Не удалось оформить заказ. Попробуйте ещё раз.',
    emptyRedirect: 'Корзина пуста',
    cityError: 'Укажите город',
    offerError: 'Нужно согласие с офертой',
  },
  product: {
    outOfStock: 'Нет в наличии',
    addToCart: 'В корзину',
    original: 'Оригинал',
    perMl: '/ 1 мл',
    razliv: 'Разлив',
    raspiv: 'Распив',
    hit: 'Хит',
    isNew: 'Новинка',
    favoriteAdd: 'В избранное',
    favoriteRemove: 'Убрать из избранного',
    formatRazliv: 'Разлив — налив из общей линейки, цена за миллилитр одна.',
    formatRaspiv: 'Распив — отливант из фирменного флакона, не копия.',
    kaspi: 'Оплата Kaspi после подтверждения',
    delivery: 'Доставка: уточним в WhatsApp',
    similar: 'Похожие',
    notes: 'Ноты',
    notesTop: 'Верх',
    notesMiddle: 'Сердце',
    notesBase: 'База',
  },
  catalog: {
    filters: 'Фильтры',
    openWhatsApp: 'WhatsApp',
    all: 'Все ароматы',
    tabAll: 'Все',
    razliv: 'Разлив',
    raspiv: 'Распив',
    leadAll: 'Разлив и оригинальный распив. Объём выбираете на карточке.',
    leadRazliv: '800 ₸ за 1 мл. 5, 10 или 20 мл.',
    leadRaspiv: 'Оригинал из фирменного флакона, не копия.',
    searchPlaceholder: 'Поиск по названию',
    searchLabel: 'Поиск аромата',
    searchClear: 'Очистить поиск',
    searchClose: 'Закрыть поиск',
    reset: 'Сбросить',
    empty: 'Ничего не найдено',
    emptyRaspiv: 'Распива в наличии сейчас нет.',
    emptyRaspivLead: 'В каталоге — разлив. 5, 10 или 20 мл.',
    emptyRaspivCta: 'Смотреть разлив',
    retry: 'Повторить',
    loadError: 'Не удалось загрузить каталог',
    sort: 'Сортировка',
    sortPopular: 'По популярности',
    sortPriceAsc: 'Цена: по возрастанию',
    sortPriceDesc: 'Цена: по убыванию',
    sortName: 'По названию',
    gender: 'Пол',
    brand: 'Бренд',
    allBrands: 'Все бренды',
    family: 'Семейство',
    price: 'Цена за 5 мл',
    stock: 'Наличие',
    stockAll: 'Все',
    stockIn: 'В наличии',
    stockOut: 'Нет в наличии',
    popular: 'Часто ищут',
  },
  nav: {
    catalog: 'Каталог',
    razliv: 'Разлив',
    raspiv: 'Распив',
    how: 'Как это работает',
    favorites: 'Избранное',
    cart: 'Корзина',
    search: 'Поиск',
    whatsapp: 'WhatsApp',
  },
  home: {
    heroTitle: 'Оригинальная парфюмерия по миллилитру',
    heroLead: 'Разлив и распив. 5, 10 или 20 мл. Заказ в WhatsApp, оплата Kaspi.',
    shop: 'Смотреть ароматы',
    howLink: 'Как устроен распив',
    hits: 'Хиты',
    allAromas: 'Все ароматы',
    step1Title: 'Аромат',
    step1: 'Выбираете аромат',
    step2Title: 'Объём',
    step2: 'Ставите 5, 10 или 20 мл',
    step3Title: 'WhatsApp · Kaspi',
    step3: 'Пишете в WhatsApp, оплата Kaspi',
    raspivLine: 'Распив — отливант из фирменного флакона.',
    razlivTitle: 'Разлив',
    razlivLead: 'Одна цена за миллилитр на линейку. 5, 10 или 20 мл.',
    razlivPrice: '800 ₸ / мл',
    raspivTitle: 'Распив',
    raspivLead: 'Оригинал из фирменного флакона, не копия.',
    trustKaspi: 'Оплата Kaspi после подтверждения',
    trustWhatsApp: 'Заказ и консультация в WhatsApp',
    trustVolume: 'Объём 5, 10 или 20 мл на карточке',
    trustOriginal: 'Распив — отливант из фирменного флакона',
    stories: 'Истории известных парфюмеров',
    setsTitle: 'Наборы пробников',
    setsLead: 'Не уверены? Закажите набор из 4 пробников по 2 мл и найдите «свой» аромат',
    setPlaceholder: 'SAMPLE SET',
    setCta: 'Добавить в корзину',
    newsletterKicker: 'Подписка',
    newsletterTitle: 'Получайте персональные рекомендации',
    newsletterLead:
      'Новинки, эксклюзивные подборки и доступ к закрытым распивам. Никакого спама — только аромат.',
    newsletterPlaceholder: 'Ваш email',
    newsletterSubmit: 'Подписаться',
    newsletterWhatsApp: 'Напишите нам в WhatsApp — отдельной рассылки пока нет.',
  },
  how: {
    title: 'Как это работает',
    intro: 'Оригинальная парфюмерия миллилитрами. Три шага до WhatsApp.',
    originTitle: 'Откуда аромат',
    origin: 'Распив — отливант из фирменного флакона, не копия и не аналог. Разлив — налив из общей линейки по одной цене за миллилитр.',
    pourTitle: 'Как наливаем',
    pour: 'Вы выбираете 5, 10 или 20 мл на карточке. В заказ уходит тот объём и тот формат, что в корзине.',
    payTitle: 'Как платить',
    pay: 'Отправляете заказ с сайта. Мы подтверждаем состав в WhatsApp. Оплата — Kaspi после подтверждения. Доставку согласуем там же.',
    guaranteeTitle: 'Гарантия',
    guarantee: 'Объём и формат в заказе совпадают с тем, что вы выбрали.',
  },
  legal: {
    ofertaTitle: 'Публичная оферта',
    ofertaPreparing: 'Публичная оферта находится в процессе подготовки.',
    privacyTitle: 'Политика конфиденциальности',
    privacyUpdated: 'Обновлено 31 августа 2026 года.',
  },
  favorites: {
    title: 'Избранное',
    empty: 'Пока пусто',
    toCatalog: 'В каталог',
  },
  footer: {
    nav: 'Навигация',
    contacts: 'Контакты',
    legal: 'Документы',
    city: 'г. Павлодар',
    addressLabel: 'Адрес',
    address: 'Н. Назарбаева 283/1',
    hoursLabel: 'Время работы',
    hours: '10:00 – 20:00',
    copyright: '© 2026 Lumira Parfume. Все права защищены.',
  },
  notFound: {
    title: 'Страница не найдена',
    lead: 'Такой страницы нет. Можно вернуться в каталог.',
    cta: 'В каталог',
  },
  gender: {
    all: 'Все',
    male: 'Мужской',
    female: 'Женский',
    unisex: 'Унисекс',
  },
  admin: {
    title: 'Админка Lumira',
    login: 'Войти',
    logout: 'Выйти',
    email: 'Email',
    password: 'Пароль',
    forbidden: 'Нет доступа к админке.',
    products: 'Товары',
    orders: 'Заказы',
    inStock: 'В наличии',
    hidden: 'Скрыто',
    pricePerMl: 'Цена за мл',
    telegramSent: 'Telegram',
    status: 'Статус',
  },
} as const
